[package]
name = "arctk"
version = "0.14.6"
authors = ["Freddy Wordingham <fjmw201@exeter.ac.uk>"]
description = "Physics simulation library and binaries"
repository = "https://github.com/FreddyWordingham/arctk"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["physics", "mcrt", "ode", "diffusion", "rt"]
categories = ["science", "simulation"]
edition = "2018"
documentation = "https://freddywordingham.github.io/arctk"
exclude = ["docs/", "input/", "output/"]

[features]
# default = ["netcdf", "png"]

[dependencies]
# arctk-attr = { path = "../arctk-attr" }
# arctk-proc = { path = "../arctk-proc" }
arctk-attr = "0.3.*"
arctk-proc = "0.4.*"

ansi_rgb = "0.2.*"
colored = "2.0.*"
hex = "0.4.*"
indicatif = "0.15.*"
json5 = "0.3.*"
lazy_static = "1.4.*"
nalgebra = { version = "0.24.1", features = ["serde-serialize"] }
ndarray = { version = "0.13.*", features = ["rayon", "serde-1"] }
ndarray-parallel = "0.9.*"
ndarray-stats = "0.3.*"
netcdf = { version = "0.6.*", optional = true }
num_cpus = "1.13.*"
palette = "0.5.*"
physical_constants = "0.3.*"
png = { version = "0.16.*", optional = true }
rand = "0.8.*"
rayon = "1.5.*"
rgb = "0.8.*"
rltk = { version = "0.8.*", optional = true }
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"
slice-of-array = "0.2.*"
specs = { version = "0.16.*", optional = true }
specs-derive = { version = "0.4.*", optional = true }
terminal_size = "0.1.*"

[[bin]]
name = "babbage"
required-features = ["netcdf"]

[[bin]]
name = "cartographer"
required-features = ["netcdf"]

[[bin]]
name = "diffuse"
required-features = ["netcdf"]

[[bin]]
name = "flask"

[[bin]]
name = "reactor"
required-features = ["netcdf"]

# [[bin]]
# name = "mcrt"
# required-features = ["netcdf"]

[[bin]]
name = "render"
required-features = ["png"]

[profile.dev]
# Development profile: "cargo build".
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

# [profile.release]
# # Release profile: "cargo build --release"
# # # [DEV RELEASE]
# opt-level = 3
# debug = true
# rpath = false
# lto = false
# debug-assertions = true
# codegen-units = 16
# panic = "unwind"
# incremental = false
# overflow-checks = true

[profile.release]
# [RELEASE]
# Release profile: "cargo build --release"
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false

[profile.test]
# Testing profile: "cargo test"
opt-level = 0
debug = 2
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
incremental = true
overflow-checks = true

[profile.bench]
# Benchmark profile: "cargo bench" (and "cargo test --release)".
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[package.metadata.docs.rs]
no-default-features = true
default-target = "x86_64-apple-darwin"
targets = ["x86_64-unknown-linux-gnu"]
