[package]
name = "arctk"
version = "0.1.0"
description = "Example library and binaries."
authors = ["Freddy Wordingham <fjmw201@exeter.ac.uk>"]
edition = "2018"
repository = "https://github.com/FreddyWordingham/arctk"
readme = "README.md"
license = "license.txt"
keywords = ["physics", "mcrt", "ode", "diffusion", "rt"]
categories = ["science", "simulation"]
# default-run = "render"

[dependencies]
attr = { path = "res/crates/attr" }
proc = { path = "res/crates/proc" }

ansi_rgb = "0.2.0"
colored = "1.9.3"
hex = "0.4.2"
indicatif = "0.15.0"
json5 = "0.2.8"
lazy_static = "1.4.0"
minifb = "0.17.0"
nalgebra = { version = "0.21.1", features = ["serde-serialize"] }
ndarray = { version = "0.13.1", features = ["rayon", "serde-1"] }
ndarray-parallel = "0.9.1"
num_cpus = "1.13.0"
palette = "0.5.0"
physical_constants = "0.3.0"
png = "0.16.6"
rand = "0.7.3"
rayon = "1.3.1"
rgb = "0.8.20"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
slice-of-array = "0.2.1"
terminal_size = "0.1.13"

[profile.dev]
# Development profile: "cargo build".
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

[profile.release]
# Release profile: "cargo build --release"
# # [DEV RELEASE]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = "unwind"
incremental = false
overflow-checks = true

# [profile.release]
# # [RELEASE]
# # Release profile: "cargo build --release"
# opt-level = 3
# debug = false
# rpath = false
# lto = "fat"
# debug-assertions = false
# codegen-units = 1
# panic = "abort"
# incremental = false
# overflow-checks = false

[profile.test]
# Testing profile: "cargo test"
opt-level = 0
debug = 2
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
incremental = true
overflow-checks = true

[profile.bench]
# Benchmark profile: "cargo bench" (and "cargo test --release)".
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false
