[package]
authors = ["Freddy Wordingham <fjmw201@exeter.ac.uk>"]
name = "arctk"
version = "0.9.4"
description = "Physics simulation library and binaries."
repository = "https://github.com/FreddyWordingham/arctk"
readme = "README.md"
keywords = ["physics", "mcrt", "ode", "diffusion", "rt"]
categories = ["science", "simulation"]
edition = "2018"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/arctk"

[features]
default = ["netcdf"]

[dependencies]
arctk-attr = "0.1.*"
arctk-proc = "0.1.*"
# arctk-attr = { path = "../arctk-attr" }
# arctk-proc = { path = "../arctk-proc" }

ansi_rgb = "0.2.*"
colored = "2.0.*"
hex = "0.4.*"
indicatif = "0.15.*"
json5 = "0.2.*"
nalgebra = { version = "0.22.*", features = ["serde-serialize"] }
ndarray = { version = "0.13.*", features = ["rayon", "serde-1"] }
ndarray-parallel = "0.9.*"
ndarray-stats = "0.3.*"
netcdf = { version = "0.5.*", optional = true }
palette = "0.5.*"
png = "0.16.*"
rgb = "0.8.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"
slice-of-array = "0.2.*"
terminal_size = "0.1.*"
rand = "0.7.*"
lazy_static = "1.4.*"

[profile.dev]
# Development profile: "cargo build".
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

[profile.release]
# Release profile: "cargo build --release"
# # [DEV RELEASE]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = "unwind"
incremental = false
overflow-checks = true

# [profile.release]
# # [RELEASE]
# # Release profile: "cargo build --release"
# opt-level = 3
# debug = false
# rpath = false
# lto = "fat"
# debug-assertions = false
# codegen-units = 1
# panic = "abort"
# incremental = false
# overflow-checks = false

[profile.test]
# Testing profile: "cargo test"
opt-level = 0
debug = 2
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
incremental = true
overflow-checks = true

[profile.bench]
# Benchmark profile: "cargo bench" (and "cargo test --release)".
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[package.metadata.docs.rs]
no-default-features = true
default-target = "x86_64-apple-darwin"
targets = ["x86_64-unknown-linux-gnu"]
