[package]
authors = ["Freddy Wordingham <fjmw201@exeter.ac.uk>"]
name = "arctk"
version = "0.1.0"
description = "Physics simulation library and binaries."
repository = "https://github.com/FreddyWordingham/arctk"
readme = "README.md"
keywords = ["physics", "mcrt", "ode", "diffusion", "rt"]
categories = ["science", "simulation"]
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
# netcdf = []

[dependencies]
arctk-attr = "0.1.*"
arctk-proc = "0.1.*"
serde = { version = "1.0.*", features = ["derive"] }
ndarray = { version = "0.13.*", features = ["rayon", "serde-1"] }
ndarray-parallel = "0.9.*"
ndarray-stats = "0.3.*"
serde_json = "1.0.*"
json5 = "0.2.*"

# netcdf = {version = "0.5.*", optional = true }

[profile.dev]
# Development profile: "cargo build".
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

[profile.release]
# Release profile: "cargo build --release"
# # [DEV RELEASE]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = "unwind"
incremental = false
overflow-checks = true

# [profile.release]
# # [RELEASE]
# # Release profile: "cargo build --release"
# opt-level = 3
# debug = false
# rpath = false
# lto = "fat"
# debug-assertions = false
# codegen-units = 1
# panic = "abort"
# incremental = false
# overflow-checks = false

[profile.test]
# Testing profile: "cargo test"
opt-level = 0
debug = 2
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
incremental = true
overflow-checks = true

[profile.bench]
# Benchmark profile: "cargo bench" (and "cargo test --release)".
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false
